export default {
  // settings from settings page
  // for each image, how long they took and rating
  session: [
    {
      id: 0,
    },
  ],
  phobia: [
    {
      id: 'acrophobia',
    },
    {
      id: 'anthophobia',
    },
    {
      id: 'arachnophobia',
    },
    {
      id: 'chronomentrophobia',
    },
    {
      id: 'dendrophobia',
    },
    {
      id: 'herpetophobia',
    },
    {
      id: 'thalassophobia',
    },
    {
      id: 'trypophobia',
    },
  ],
  images: [
    {
      id: 0,
      title: 'Women diving in the deep sea',
      url: 'https://drive.google.com/drive/u/0/folders/1HPQCbQb_VI3yFGb_O08fXmXpHwAGn6h4',
      scariness: 'mild',
      phobium_id: 'thalassophobia',
    },
    {
      id: 1,
      title: 'Interior of sunken ship',
      url: 'https://drive.google.com/file/d/1CGykngT_-W6giC5iBaiZexkRyflnF0UB/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'thalassophobia',
    },
    {
      id: 2,
      title: 'Diver with weird sea creature',
      url: 'https://drive.google.com/file/d/10nxPaf9M98P2mVxdz8S56AGIPP0zqMr5/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'thalassophobia',
    },
    {
      id: 3,
      title: 'Baby floating in polluted water',
      url: 'https://drive.google.com/file/d/1sGKNm3vv10HyqEM4-wn5u7i5SwW6sie1/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'thalassophobia',
    },
    {
      id: 4,
      title: 'Ship sailing in bad weather',
      url: 'https://drive.google.com/file/d/14NBITvQlQUhhaxEAyGxYNk3sAsoAor00/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'thalassophobia',
    },
    {
      id: 5,
      title: 'Very dark pool',
      url: 'https://drive.google.com/file/d/1Eu1B3nGZloV3mespSa2_1BYIwvlkFPMm/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'thalassophobia',
    },
    {
      id: 6,
      title: 'Swimmer in deep cave with trees',
      url: 'https://drive.google.com/file/d/1_tKO3mG3VThr5BvcHezxPodJI6fj_90x/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'thalassophobia',
    },
    {
      id: 7,
      title: 'Kids jumping into deep pond',
      url: 'https://drive.google.com/file/d/1_tKO3mG3VThr5BvcHezxPodJI6fj_90x/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'thalassophobia',
    },
    {
      id: 7,
      title: 'Beach near very drop off',
      url: 'https://drive.google.com/file/d/1VXhWopxVTBp370PJNgt6qtME9gN-FCuh/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'thalassophobia',
    },
    {
      id: 8,
      title: 'Bark with holes',
      url: 'https://drive.google.com/file/d/1Hx7zibSMzLCwsa-If9L7teLszW4ZieYa/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'trypophobia',
    },
    {
      id: 9,
      title: 'Wooden structure with lots of holes',
      url: 'https://drive.google.com/file/d/1yeS7YZe0zNWjLD5J3TwKr8acXBGlSru0/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'trypophobia',
    },
    {
      id: 10,
      title: 'Building with holes on the side',
      url: 'https://drive.google.com/file/d/1PpbhALoDbJXvILBRz7IqhNr9LnT8KzH5/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'trypophobia',
    },
    {
      id: 11,
      title: 'Weird water structure with lots of holes',
      url: 'https://drive.google.com/file/d/1vCgvhjpXQpxJQeAnW-5o2n2zTH44xt1c/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'trypophobia',
    },
    {
      id: 12,
      title: 'Petri dish with circular bubbles',
      url: 'https://drive.google.com/file/d/1OUlsmHxfX1MQh_cA110xMINiKCCi04J_/view?usp=sharing',
      scariness: 'middle',
      phobium_id: 'trypophobia',
    },
    {
      id: 13,
      title: 'Mac N Cheese Meatloaf',
      url: 'https://drive.google.com/file/d/1n3dUFPxcMw2dKrN5Iy8IzWSzF2qtWoTk/view?usp=sharing',
      scariness: 'middle',
      phobium_id: 'trypophobia',
    },
    {
      id: 14,
      title: 'Load with small imprints',
      url: 'https://drive.google.com/file/d/1JD7VSb97nWk_H3yWgL4gaYaZLb8oAhhU/view?usp=sharing',
      scariness: 'middle',
      phobium_id: 'trypophobia',
    },
    {
      id: 15,
      title: 'Berries in liquid',
      url: 'https://drive.google.com/file/d/1NfJ9xfoNZQyuddszpWbT_6tXVsymqyJS/view?usp=sharing',
      scariness: 'middle',
      phobium_id: 'trypophobia',
    },
    {
      id: 16,
      title: 'Trypophobia toy',
      url: 'https://drive.google.com/file/d/1RczMyOnn_m5gFTNOirTW_egvmnqPGlSp/view?usp=sharing',
      scariness: 'middle',
      phobium_id: 'trypophobia',
    },
    {
      id: 17,
      title: 'Donald Trump with coronavirus on his face',
      url: 'https://drive.google.com/file/d/1vM21f-3Jzqoxg2wFdGjkPTGuxHZfgCOp/view?usp=sharing',
      scariness: 'middle',
      phobium_id: 'trypophobia',
    },
    {
      id: 18,
      title: 'Small sculpture with lots of holes',
      url: 'https://drive.google.com/file/d/181vd32t1Rai5nolT7_bIL22uX5R50V3B/view?usp=sharing',
      scariness: 'spicey',
      phobium_id: 'trypophobia',
    },
    {
      id: 19,
      title: 'Bones surrounded by rocks with tiny bubbles',
      url: 'https://drive.google.com/file/d/1vd8RSB3Fy6JpI4xpNQX6MabC9df5tqhS/view?usp=sharing',
      scariness: 'spicey',
      phobium_id: 'trypophobia',
    },
    {
      id: 20,
      title: 'Truck carrying pipes of different sizes',
      url: 'https://drive.google.com/file/d/1M7yK4bOEEt05A2VkA24N19BYAyC3X0SO/view?usp=sharing',
      scariness: 'spicey',
      phobium_id: 'trypophobia',
    },
    {
      id: 21,
      title: 'Small spider in flower',
      url: 'https://drive.google.com/file/d/1CJ6vUL_fljRLMxEjJoMb49HnUH6IikRf/view?usp=sharing',
      scariness: 'mild',
      phobium_id: 'arachnophobia',
    },
    {
      id: 22,
      title: 'Mommy spider hanging',
      url: 'https://drive.google.com/file/d/1w4HbIgel3aoYwq40OvygqLmAo65r6nxt/view?usp=sharing',
      scariness: 'middle',
      phobium_id: 'arachnophobia',
    },
    {
      id: 23,
      title: 'Mommy spider hanging',
      url: 'https://drive.google.com/file/d/1ogsbg7DmboqZ88qkl0jTtjGJTsOp-NgO/view?usp=sharing',
      scariness: 'spicey',
      phobium_id: 'arachnophobia',
    },
  ],
};
